# -*- coding: utf-8 -*-
"""Factorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/160gbyeMA70p1xHe-As8QN36EeJfVTWob
"""

x= 5
fact = 1
for i in range(1,x+1):
  fact = fact*i
print(fact)